/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee.time.tracking.system;
import java.util.Timer;
import java.util.TimerTask;

class LoginTimer extends TimerTask
{
    private LoginFrame loginFrame;
    
    LoginTimer(LoginFrame loginFrame)
    {
        this.loginFrame = loginFrame;
    }
    
    @Override
    public void run()
    {
        loginFrame.loginTimerExpired();
    }
    
    public void cancelTimer()
    {
        this.cancel();
    }
}
/**
 *
 * @author InanEvin
 */
public class LoginFrame extends javax.swing.JFrame
{

    private Timer loginTimer;
    private LoginTimer loginTimerTask;
    
    /**
     * Creates new form LoginFrame
     */
    public LoginFrame()
    {
        initComponents();
        errorLabel.setVisible(false);
    }
    
    public void loginTimerExpired()
    {
        errorLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        gradientPanel1 = new employee.time.tracking.system.GradientPanel();
        errorLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        infoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Time Tracking System Login");
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Ebrima", 0, 10)); // NOI18N
        setForeground(java.awt.Color.white);
        setPreferredSize(new java.awt.Dimension(512, 256));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        gradientPanel1.setColorBegin(new java.awt.Color(66, 134, 244));
        gradientPanel1.setColorEnd(new java.awt.Color(55, 59, 68));
        gradientPanel1.setPreferredSize(new java.awt.Dimension(300, 25));
        gradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        errorLabel.setFont(new java.awt.Font("Prototype", 0, 14)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(255, 51, 51));
        errorLabel.setText("The e-mail address you have entered is not valid!");
        gradientPanel1.add(errorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 310, -1));

        emailField.setFont(new java.awt.Font("Prototype", 0, 14)); // NOI18N
        emailField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        gradientPanel1.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 280, 30));

        loginButton.setFont(new java.awt.Font("Prototype", 0, 12)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                loginButtonActionPerformed(evt);
            }
        });
        gradientPanel1.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, 30));

        infoLabel.setFont(new java.awt.Font("Prototype", 0, 18)); // NOI18N
        infoLabel.setForeground(new java.awt.Color(255, 255, 255));
        infoLabel.setText("Please enter your employee e-mail address below to login.");
        gradientPanel1.add(infoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 480, -1));

        getContentPane().add(gradientPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_loginButtonActionPerformed
    {//GEN-HEADEREND:event_loginButtonActionPerformed
        // TODO add your handling code here:
        String email = emailField.getText();
        if(Utility.validateEmail(email))
        {
            // Login Successfull
            dispose();
        }
        else
        {
            if(loginTimerTask != null)
                loginTimerTask.cancelTimer();
            
            loginTimerTask = new LoginTimer(this);
            loginTimer = new Timer();
            loginTimer.schedule(loginTimerTask, 3000);
            errorLabel.setVisible(true);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel errorLabel;
    private employee.time.tracking.system.GradientPanel gradientPanel1;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JButton loginButton;
    // End of variables declaration//GEN-END:variables
}
